### PR TITLE
[add] yargs to handle cli args

### PR DESCRIPTION
**Pull request by HenryTabima**
### index.js
Now the index file export a function where yargs define how the cli will work
### bin/vuepress-jsdoc
Just require the new `index.js` file and execute it
### cmds/generate.js
This file export  a function wich have most of the code that had the previous index.js
### package.json
Update bin path and add yargs dependecy
### example/package.json
Update the script `docs` to use `../bin/vuepress-jsdoc` instead `../index.js`

## Comment
I tested the code with the example folder and it works fine

### CODE REVIEW

**Review by ph1p — CHANGES_REQUESTED** [review]
First. Thanks for contribution ;) I'm fine with the use of yargs, but I have some suggestions.
* Add all important information to the README.md (--help, aliases: ['gen', 'g', '$0'] etc.)
* Install the dependencies with yarn and remove the package-lock.json. It shouldn't affect anything, but I switched to it, because of one hint inside the vuepress docs.

>WARNING
>It is currently recommended to use Yarn instead of npm when installing VuePress into an existing >project that has webpack 3.x as a dependency. Npm fails to generate the correct dependency tree >in this case.
>https://vuepress.vuejs.org/guide/getting-started.html#inside-an-existing-project

* Please do not replace an entire file. Use `git mv`. I can not see what changes you've done to `cmds/generate.js`.

**Comment by HenryTabima** [comment]
ok, im going to do the changes and keep using yarn in this project. Im happy to contribute. and I didnt know about the use of `git mv`, thanks for ti. 

question: what i should do now? create a new barnch and new pull request or edit this branch and then... (dont know whats next)

**Comment by ph1p** [comment]
Hey! I'll write you a small tutorial tomorrow. No need to create a new branch ... You can force push your new changes ... If this is to complicated, you surely can open a new branch.

**Comment by ph1p** [comment]
Ok I will close this PR, because of your second one ;)

**Pull request closed without merging**
