### PR TITLE
A newline is needed at the end of this file

### PR DESCRIPTION
**Pull request by nriesco**
If that newline is not present, in macosx + nodejs@v12.15.0 it will mix the name of a function with its own description, so

```
@function someFunct
@description someDescription
...
```
will end up like `someFunct(param1, param2) => someReturn someDescription`

The newline helps mitigating that problem (the arrow still will be shown in the leftbar menu).

Anyway, is always a good practice to add a newline on everyfile.

### CODE REVIEW

**Review by ph1p — APPROVED** [review]

**Comment by ph1p** [comment]
Thank you! (:

**Comment by nriesco** [comment]
Thanks to you @ph1p ! 

There is still an issue, I spend a couple of hours trying to understand why it failed and it might be one of the dependencies itself, It's hard for me to tell. I even tried to write the issue here in Github, but couldn't make a point.

This is how the error looks like (after adding the newline) it will add an arrow (⇒) like this:

image

**Comment by ph1p** [comment]
I'll have a look at it! Thanks for reporting it. Maybe this is just a style problem and I can add a small option to enable/disable it or so.

**Comment by ph1p** [comment]
Unfortunately this is a part of jsdoc2markdown https://github.com/jsdoc2md/dmd/blob/546aa0fba9cdbd4c389619a15ba5e80706387fde/helpers/ddata.js#L329 I have added a new command for you. With `--partials' you can configure the template particles used. I have added a small example in the example folder.

**Pull request merged**
